organizations:
  - organization:
      name: "hyperledger"
  - organization:
      name: "hyperledger-labs"
days: 7
filename: "data.json"
pr-summary-filename: "pr-summary.html"
release-summary-filename: "release-summary.html"
